/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/HelloWorld copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Question: typeof import('./src/components/Question.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step: typeof import('./src/components/Step.vue')['default']
  }
}
